# Generated by Django 4.0.2 on 2022-02-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emoticon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=45)),
                ('title', models.CharField(blank=True, max_length=45, null=True)),
                ('artist', models.CharField(blank=True, max_length=20, null=True)),
                ('img', models.CharField(blank=True, max_length=500, null=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'emoticon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmoticonDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'emoticon_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmoticonOk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=45, null=True)),
                ('artist', models.CharField(blank=True, max_length=45, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('canceldate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'emoticon_ok',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('title', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'likes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('idnum', models.AutoField(db_column='idNum', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=20)),
                ('password', models.CharField(db_column='Password', max_length=20)),
                ('sex', models.CharField(db_column='Sex', max_length=2)),
                ('email', models.CharField(db_column='Email', max_length=30)),
                ('birth', models.DateField(db_column='Birth')),
                ('phonenumber', models.CharField(db_column='Phonenumber', max_length=11)),
                ('type', models.CharField(db_column='Type', max_length=45)),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('title', models.CharField(blank=True, max_length=45, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('refunddate', models.DateField(blank=True, null=True)),
                ('account', models.CharField(blank=True, max_length=45, null=True)),
                ('price', models.CharField(blank=True, max_length=45, null=True)),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'refund',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'sell',
                'managed': False,
            },
        ),
    ]
