# Generated by Django 4.0.2 on 2022-02-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emoticon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=45, null=True)),
                ('title', models.CharField(blank=True, max_length=45, null=True)),
                ('artist', models.CharField(blank=True, max_length=20, null=True)),
                ('img', models.CharField(blank=True, max_length=500, null=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'emoticon',
                'managed': False,
            },
        ),
    ]
